This iPython Notebook serves as the python code for all the machine learning algorithms as well as feature engineering performed for the project "Vehicular Crash Analysis - Prediciting Accident Severity and Crash frequency in Washington D.C."by Adarsh, Isha and Kuhu. The algorithms performed as well as the results obtained from the predictions can be seen here. 

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
#Reading the dataset
df=pd.read_csv('/Users/Adiii/Documents/Fall 2016/INFM 750/Project/df_rq1.csv')

In [4]:
df.head()

HOUROFDAY DAYOFWEEK  ACCIDENTTYPE CONSTRUCTION  \
0         13    Friday  Prop. Damage            N   
1         19    Sunday        Injury            N   
2         17  Thursday        Injury            N   
3         19  Thursday  Prop. Damage            N   
4         19  Thursday  Prop. Damage            N   

                       ONSTREET   COLLISIONTYPE ROADSURFACE  ROADTYPE  \
0                         Other    Fixed Object    Concrete  Straight   
1           Not at Intersection  Parked Vehicle     Asphalt  Straight   
2  Within 100ft of Intersection     Side Swiped     Asphalt  Straight   
3  Within 100ft of Intersection     Side Swiped     Asphalt             
4           Not at Intersection     Side Swiped     Asphalt             

  ROADCONDITION        STREETLIGHT  LIGHTCONDITION WEATHER TRAFFICCONDITION  \
0           Dry  Street Lights Off        Daylight   Clear            Light   
1           Dry  Street Lights Off        Daylight                            
2           Dry   Street Lights On  Dark (Lighted)   Clear            Light   
3           Dry   Street Lights On  Dark (Lighted)   Clear            Light   
4           Wet            Unknown         Unknown    Rain          Unknown   

            ROADWAYTYPE TRAFFICCONTROL STREETTYPE QUADRANT  FREQBYLENGTH  
0                 Other        Unknown         ST       SE      0.001535  
1  Two-Way, Not Divided           None         ST       SE      0.001535  
2  Two-Way, Not Divided           None         ST       SE      0.001535  
3  Two-Way, Not Divided           None         ST       SE      0.001535  
4  Two-Way, Not Divided           None        AVE       SE      0.000930

In [5]:
df.dtypes

HOUROFDAY             int64
DAYOFWEEK            object
ACCIDENTTYPE         object
CONSTRUCTION         object
ONSTREET             object
COLLISIONTYPE        object
ROADSURFACE          object
ROADTYPE             object
ROADCONDITION        object
STREETLIGHT          object
LIGHTCONDITION       object
WEATHER              object
TRAFFICCONDITION     object
ROADWAYTYPE          object
TRAFFICCONTROL       object
STREETTYPE           object
QUADRANT             object
FREQBYLENGTH        float64
dtype: object

In [6]:
from sklearn.metrics import accuracy_score

In [7]:
from sklearn.cross_validation import KFold

//anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [8]:
from sklearn.cross_validation import train_test_split

In [9]:
#Defining a function for cross validation score
cv_score(clf, x, y, score_func=accuracy_score):
        result = 0
        nfold = 5
        for train, test in KFold(y.size, nfold):
                 clf.fit(x[train], y[train])
                 result += score_func(clf.predict(x[test]), y[test])
        return result / nfold

In [10]:
df1=df.copy()

In [11]:
#Converting the catergorical features to data type category
df1['ACCIDENTTYPE']=df1['ACCIDENTTYPE'].astype('category')
df1['CONSTRUCTION']=df1['CONSTRUCTION'].astype('category')
df1['ONSTREET']=df1['ONSTREET'].astype('category')
df1['COLLISIONTYPE']=df1['COLLISIONTYPE'].astype('category')
df1['ROADSURFACE']=df1['ROADSURFACE'].astype('category')
df1['ROADTYPE']=df1['ROADTYPE'].astype('category')
df1['ROADCONDITION']=df1['ROADCONDITION'].astype('category')
df1['STREETLIGHT']=df1['STREETLIGHT'].astype('category')
df1['LIGHTCONDITION']=df1['LIGHTCONDITION'].astype('category')
df1['WEATHER']=df1['WEATHER'].astype('category')
df1['TRAFFICCONDITION']=df1['TRAFFICCONDITION'].astype('category')
df1['ROADWAYTYPE']=df1['ROADWAYTYPE'].astype('category')
df1['TRAFFICCONTROL']=df1['TRAFFICCONTROL'].astype('category')
df1['HOUROFDAY']=df1['HOUROFDAY'].astype('category')
df1['DAYOFWEEK']=df1['DAYOFWEEK'].astype('category')
df1['STREETTYPE']=df1['STREETTYPE'].astype('category')
df1['QUADRANT']=df1['QUADRANT'].astype('category')                                       

In [12]:
df1.dtypes

HOUROFDAY           category
DAYOFWEEK           category
ACCIDENTTYPE        category
CONSTRUCTION        category
ONSTREET            category
COLLISIONTYPE       category
ROADSURFACE         category
ROADTYPE            category
ROADCONDITION       category
STREETLIGHT         category
LIGHTCONDITION      category
WEATHER             category
TRAFFICCONDITION    category
ROADWAYTYPE         category
TRAFFICCONTROL      category
STREETTYPE          category
QUADRANT            category
FREQBYLENGTH         float64
dtype: object

In [13]:
dfy=df1[['ACCIDENTTYPE']]

In [14]:
del df1['ACCIDENTTYPE']

In [15]:
#One hot encoding the features using pandas.get_dummies function
dfx=pd.get_dummies(df1)

In [16]:
#Creating training and testing set
Xtr, Xtest, ytr, ytest = train_test_split(dfx.values, dfy.values)

In [17]:
dfx.shape

(66305, 165)

In [18]:
dfx.head()

FREQBYLENGTH  HOUROFDAY_0  HOUROFDAY_1  HOUROFDAY_2  HOUROFDAY_3  \
0      0.001535          0.0          0.0          0.0          0.0   
1      0.001535          0.0          0.0          0.0          0.0   
2      0.001535          0.0          0.0          0.0          0.0   
3      0.001535          0.0          0.0          0.0          0.0   
4      0.000930          0.0          0.0          0.0          0.0   

   HOUROFDAY_4  HOUROFDAY_5  HOUROFDAY_6  HOUROFDAY_7  HOUROFDAY_8  \
0          0.0          0.0          0.0          0.0          0.0   
1          0.0          0.0          0.0          0.0          0.0   
2          0.0          0.0          0.0          0.0          0.0   
3          0.0          0.0          0.0          0.0          0.0   
4          0.0          0.0          0.0          0.0          0.0   

      ...       STREETTYPE_RD  STREETTYPE_SQ  STREETTYPE_ST  STREETTYPE_TER  \
0     ...                 0.0            0.0            1.0             0.0   
1     ...                 0.0            0.0            1.0             0.0   
2     ...                 0.0            0.0            1.0             0.0   
3     ...                 0.0            0.0            1.0             0.0   
4     ...                 0.0            0.0            0.0             0.0   

   STREETTYPE_WAY  QUADRANT_BN  QUADRANT_NE  QUADRANT_NW  QUADRANT_SE  \
0             0.0          0.0          0.0          0.0          1.0   
1             0.0          0.0          0.0          0.0          1.0   
2             0.0          0.0          0.0          0.0          1.0   
3             0.0          0.0          0.0          0.0          1.0   
4             0.0          0.0          0.0          0.0          1.0   

   QUADRANT_SW  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0  

[5 rows x 165 columns]

In [19]:
#Flattening into a 1-D array for running the models
ytr=ytr.ravel()
ytest=ytest.ravel()

In [20]:
from sklearn import svm

In [21]:
##LinearSVC
clfsvmlin = svm.LinearSVC(class_weight='balanced')

In [22]:
clfsvmlin.fit(Xtr, ytr)

LinearSVC(C=1.0, class_weight='balanced', dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [23]:
#For prediction
ypredsvmlin=clfsvmlin.predict(Xtest)

In [27]:
from sklearn.metrics import precision_recall_fscore_support

In [25]:
#Calculating precision,recall and f1 score
precision_recall_fscore_support(ytest, ypredsvmlin)

(array([ 0.00819672,  0.56217486,  0.76267149]),
 array([ 0.03846154,  0.56992174,  0.75002342]),
 array([ 0.01351351,  0.5660218 ,  0.75629458]),
 array([   26,  5878, 10673]))

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
from sklearn.metrics import classification_report

In [28]:
#Generating a classification report
classification_report(ytest, ypredsvmlin)

'              precision    recall  f1-score   support\n\n    Fatality       0.01      0.04      0.01        26\n      Injury       0.56      0.57      0.57      5878\nProp. Damage       0.76      0.75      0.76     10673\n\n avg / total       0.69      0.69      0.69     16577\n'

In [29]:
confusion_matrix(ytest, ypredsvmlin)

array([[   1,   14,   11],
       [  48, 3350, 2480],
       [  73, 2595, 8005]])

In [30]:
#Generating confusion matrix
cmsvmlin=pd.crosstab(ytest, ypredsvmlin, rownames=['True'], colnames=['Predicted'], margins= True)

In [32]:
cmsvmlin

Predicted     Fatality  Injury  Prop. Damage    All
True                                               
Fatality             1      14            11     26
Injury              48    3350          2480   5878
Prop. Damage        73    2595          8005  10673
All                122    5959         10496  16577

In [35]:
from sklearn.metrics import f1_score

In [34]:
f1_score(ytest, ypredsvmlin, average='weighted')

0.68766118954522581

In [71]:
cv_score(clfsvmlin, Xtest, ytest)

0.68408076750232438

In [36]:
##SVM with default rbf kernel
clfsvmrbf = svm.SVC(class_weight='balanced')

In [37]:
clfsvmrbf.fit(Xtr, ytr) 

SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [38]:
ypredsvmrbf=clfsvmrbf.predict(Xtest)

In [45]:
precision_recall_fscore_support(ytest, ypredsvmrbf)

(array([ 0.00683761,  0.47345637,  0.83951026]),
 array([ 0.46153846,  0.70704321,  0.47540523]),
 array([ 0.01347558,  0.56713974,  0.60704672]),
 array([   26,  5878, 10673]))

In [46]:
classification_report(ytest, ypredsvmrbf)

'              precision    recall  f1-score   support\n\n    Fatality       0.01      0.46      0.01        26\n      Injury       0.47      0.71      0.57      5878\nProp. Damage       0.84      0.48      0.61     10673\n\n avg / total       0.71      0.56      0.59     16577\n'

In [47]:
cmsvmrbf=pd.crosstab(ytest, ypredsvmrbf, rownames=['True'], colnames=['Predicted'], margins= True)

In [48]:
cmsvmrbf

Predicted     Fatality  Injury  Prop. Damage    All
True                                               
Fatality            12       9             5     26
Injury             757    4156           965   5878
Prop. Damage       986    4613          5074  10673
All               1755    8778          6044  16577

In [49]:
f1_score(ytest, ypredsvmrbf, average='weighted')

0.59196521540633429

In [72]:
cv_score(clfsvmrbf, Xtest, ytest)

0.59558522416111292

In [149]:
##k-NN classifier
from sklearn.neighbors import KNeighborsClassifier

In [150]:
knn = KNeighborsClassifier()

In [151]:
knn.fit(Xtr, ytr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [152]:
ypredknn=knn.predict(Xtest)

In [153]:
precision_recall_fscore_support(ytest, ypredknn)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.        ,  0.48597285,  0.6910422 ]),
 array([ 0.        ,  0.36505778,  0.78801238]),
 array([ 0.        ,  0.41692547,  0.7363485 ]),
 array([   32,  5884, 10661]))

In [159]:
cmknn=pd.crosstab(ytest, ypredknn, rownames=['True'], colnames=['Predicted'], margins= True)

In [160]:
cmknn

Predicted     Injury  Prop. Damage    All
True                                     
Fatality          12            20     32
Injury          2148          3736   5884
Prop. Damage    2260          8401  10661
All             4420         12157  16577

In [161]:
f1_score(ytest, ypredknn, average='weighted')

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.62154797402345507

In [163]:
cv_score(knn, Xtest, ytest)

0.62864218824766616

In [22]:
##Decision tree classifer
from sklearn.tree import DecisionTreeClassifier 

In [23]:
clfdt = DecisionTreeClassifier(max_features="auto",class_weight="balanced")

In [24]:
clfdt.fit(Xtr, ytr)

DecisionTreeClassifier(class_weight='balanced', criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [25]:
ypreddt=clfdt.predict(Xtest)

In [30]:
precision_recall_fscore_support(ytest, ypreddt)

(array([ 0.        ,  0.44807023,  0.6974598 ]),
 array([ 0.        ,  0.45972128,  0.68764656]),
 array([ 0.        ,  0.45382099,  0.69251842]),
 array([   32,  5884, 10661]))

In [31]:
classification_report(ytest, ypreddt)

'              precision    recall  f1-score   support\n\n    Fatality       0.00      0.00      0.00        32\n      Injury       0.45      0.46      0.45      5884\nProp. Damage       0.70      0.69      0.69     10661\n\n avg / total       0.61      0.61      0.61     16577\n'

In [32]:
cmdt=pd.crosstab(ytest, ypreddt, rownames=['True'], colnames=['Predicted'], margins= True)

In [33]:
cmdt

Predicted     Fatality  Injury  Prop. Damage    All
True                                               
Fatality             0      16            16     32
Injury              15    2705          3164   5884
Prop. Damage        14    3316          7331  10661
All                 29    6037         10511  16577

In [36]:
f1_score(ytest, ypreddt, average='weighted')

0.60645602798736153

In [37]:
cv_score(clfdt, Xtest, ytest)

0.60191853748087343

In [38]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
##Random forest classifer
clfrf10 = RandomForestClassifier(n_estimators=10,max_features="auto",class_weight="balanced")

In [43]:
clfrf10.fit(Xtr, ytr)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_split=1e-07,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [45]:
ypredrf10=clfrf10.predict(Xtest)

In [46]:
precision_recall_fscore_support(ytest, ypredrf10)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.        ,  0.52742932,  0.7256141 ]),
 array([ 0.        ,  0.47875595,  0.76475002]),
 array([ 0.        ,  0.50191537,  0.74466822]),
 array([   32,  5884, 10661]))

In [47]:
classification_report(ytest, ypredrf10)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


'              precision    recall  f1-score   support\n\n    Fatality       0.00      0.00      0.00        32\n      Injury       0.53      0.48      0.50      5884\nProp. Damage       0.73      0.76      0.74     10661\n\n avg / total       0.65      0.66      0.66     16577\n'

In [48]:
cmrf10=pd.crosstab(ytest, ypredrf10, rownames=['True'], colnames=['Predicted'], margins= True)

In [49]:
cmrf10

Predicted     Injury  Prop. Damage    All
True                                     
Fatality          16            16     32
Injury          2817          3067   5884
Prop. Damage    2508          8153  10661
All             5341         11236  16577

In [50]:
f1_score(ytest, ypredrf10, average='weighted')

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.65706568795299902

In [51]:
cv_score(clfrf10, Xtest, ytest)

0.64547236580444545

In [134]:
#Ranking the feature according importances using feature_importances attribute in Random Forests
importances=clfrf10.feature_importances_

In [135]:
std = np.std([tree.feature_importances_ for tree in clfrf10.estimators_],axis=0)

In [136]:
indices = np.argsort(importances)[::-1]

In [137]:
for f in range(Xtr.shape[1]):
        print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))


1. feature 0 (0.081412)
2. feature 44 (0.039801)
3. feature 57 (0.030891)
4. feature 53 (0.028485)
5. feature 162 (0.027976)
6. feature 119 (0.027903)
7. feature 74 (0.021587)
8. feature 161 (0.020559)
9. feature 58 (0.018999)
10. feature 77 (0.017535)
11. feature 132 (0.016468)
12. feature 157 (0.015958)
13. feature 128 (0.015452)
14. feature 141 (0.015420)
15. feature 126 (0.014994)
16. feature 81 (0.014860)
17. feature 127 (0.014545)
18. feature 99 (0.014354)
19. feature 39 (0.014257)
20. feature 21 (0.014238)
21. feature 25 (0.014007)
22. feature 124 (0.013688)
23. feature 118 (0.012643)
24. feature 96 (0.012607)
25. feature 120 (0.012223)
26. feature 36 (0.011449)
27. feature 135 (0.011437)
28. feature 35 (0.011166)
29. feature 26 (0.011040)
30. feature 103 (0.011006)
31. feature 95 (0.010791)
32. feature 29 (0.010763)
33. feature 69 (0.010661)
34. feature 31 (0.009573)
35. feature 163 (0.009548)
36. feature 18 (0.009452)
37. feature 28 (0.009209)
38. feature 30 (0.009039)
39. fea

In [52]:
#Random Forests using n_estimators as 100
clfrf100 = RandomForestClassifier(n_estimators=100,max_features="auto",class_weight="balanced")

In [53]:
clfrf100.fit(Xtr, ytr)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_split=1e-07,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [54]:
ypredrf100=clfrf100.predict(Xtest)

In [55]:
precision_recall_fscore_support(ytest, ypredrf100)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.        ,  0.58550238,  0.70647493]),
 array([ 0.        ,  0.35554045,  0.86173905]),
 array([ 0.        ,  0.4424236 ,  0.77642087]),
 array([   32,  5884, 10661]))

In [56]:
classification_report(ytest, ypredrf100)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


'              precision    recall  f1-score   support\n\n    Fatality       0.00      0.00      0.00        32\n      Injury       0.59      0.36      0.44      5884\nProp. Damage       0.71      0.86      0.78     10661\n\n avg / total       0.66      0.68      0.66     16577\n'

In [57]:
cmrf100=pd.crosstab(ytest, ypredrf100, rownames=['True'], colnames=['Predicted'], margins= True)

In [58]:
cmrf100

Predicted     Injury  Prop. Damage    All
True                                     
Fatality           7            25     32
Injury          2092          3792   5884
Prop. Damage    1474          9187  10661
All             3573         13004  16577

In [59]:
f1_score(ytest, ypredrf100, average='weighted')

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.65636987494034915

In [60]:
cv_score(clfrf100, Xtest, ytest)

0.68214974882966095

In [61]:
#Random Forests using n_estimators as 1000
clfrf1000 = RandomForestClassifier(n_estimators=1000,max_features="auto",class_weight="balanced")

In [62]:
clfrf1000.fit(Xtr, ytr)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_split=1e-07,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [63]:
ypredrf1000=clfrf1000.predict(Xtest)

In [64]:
precision_recall_fscore_support(ytest, ypredrf1000)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.        ,  0.60309748,  0.70468232]),
 array([ 0.        ,  0.33752549,  0.87806022]),
 array([ 0.        ,  0.43282118,  0.78187513]),
 array([   32,  5884, 10661]))

In [65]:
classification_report(ytest, ypredrf1000)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


'              precision    recall  f1-score   support\n\n    Fatality       0.00      0.00      0.00        32\n      Injury       0.60      0.34      0.43      5884\nProp. Damage       0.70      0.88      0.78     10661\n\n avg / total       0.67      0.68      0.66     16577\n'

In [66]:
cmrf1000=pd.crosstab(ytest, ypredrf1000, rownames=['True'], colnames=['Predicted'], margins= True)

In [67]:
cmrf1000

Predicted     Injury  Prop. Damage    All
True                                     
Fatality           7            25     32
Injury          1986          3898   5884
Prop. Damage    1300          9361  10661
All             3293         13284  16577

In [68]:
f1_score(ytest, ypredrf1000, average='weighted')

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.65646924108255433

In [69]:
cv_score(clfrf1000, Xtest, ytest)

0.68323506669068301

In [70]:
from sklearn.ensemble import ExtraTreesClassifier

In [71]:
## Extra trees classifer with number of estimators=10
clfet10 = ExtraTreesClassifier(n_estimators=10,max_features="auto",class_weight="balanced")

In [72]:
clfet10.fit(Xtr, ytr)

ExtraTreesClassifier(bootstrap=False, class_weight='balanced',
           criterion='gini', max_depth=None, max_features='auto',
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [74]:
ypredet10=clfet10.predict(Xtest)

In [75]:
precision_recall_fscore_support(ytest, ypredet10)

(array([ 0.        ,  0.51679071,  0.72365805]),
 array([ 0.        ,  0.48385452,  0.75114905]),
 array([ 0.        ,  0.49978057,  0.73714733]),
 array([   32,  5884, 10661]))

In [89]:
f1_score(ytest, ypredet10, average='weighted')

0.65147110589086865

In [76]:
## Extra trees classifer with number of estimators=100
clfet100 = ExtraTreesClassifier(n_estimators=100,max_features="auto",class_weight="balanced")

In [77]:
clfet100.fit(Xtr, ytr)

ExtraTreesClassifier(bootstrap=False, class_weight='balanced',
           criterion='gini', max_depth=None, max_features='auto',
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [78]:
ypredet100=clfet100.predict(Xtest)

In [79]:
precision_recall_fscore_support(ytest, ypredet100)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.        ,  0.56986028,  0.71167157]),
 array([ 0.        ,  0.38817131,  0.83903949]),
 array([ 0.        ,  0.4617873 ,  0.77012484]),
 array([   32,  5884, 10661]))

In [90]:
f1_score(ytest, ypredet100, average='weighted')

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.65919390686471901

In [80]:
## Extra trees classifer with number of estimators=1000
clfet1000 = ExtraTreesClassifier(n_estimators=1000,max_features="auto",class_weight="balanced")

In [81]:
clfet1000.fit(Xtr, ytr)

ExtraTreesClassifier(bootstrap=False, class_weight='balanced',
           criterion='gini', max_depth=None, max_features='auto',
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [82]:
ypredet1000=clfet1000.predict(Xtest)

In [83]:
precision_recall_fscore_support(ytest, ypredet1000)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.        ,  0.57880934,  0.71004387]),
 array([ 0.        ,  0.37508498,  0.85010787]),
 array([ 0.        ,  0.45519233,  0.77378869]),
 array([   32,  5884, 10661]))

In [84]:
classification_report(ytest, ypredet1000)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


'              precision    recall  f1-score   support\n\n    Fatality       0.00      0.00      0.00        32\n      Injury       0.58      0.38      0.46      5884\nProp. Damage       0.71      0.85      0.77     10661\n\n avg / total       0.66      0.68      0.66     16577\n'

In [85]:
cmet1000=pd.crosstab(ytest, ypredet1000, rownames=['True'], colnames=['Predicted'], margins= True)

In [86]:
cmet1000

Predicted     Injury  Prop. Damage    All
True                                     
Fatality           8            24     32
Injury          2207          3677   5884
Prop. Damage    1598          9063  10661
All             3813         12764  16577

In [87]:
f1_score(ytest, ypredet1000, average='weighted')

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.65920931715360065

In [88]:
cv_score(clfet1000, Xtest, ytest)

0.67768563043664154

In [ ]:
#Gradient Boosting Classifer with default n=100

In [109]:
from sklearn.grid_search import GridSearchCV

In [96]:
from sklearn.ensemble import GradientBoostingClassifier

In [110]:
#Tuning the hyper parameters using GridSearchCV
gs =GridSearchCV(clfgbt, param_grid={'learning_rate': [0.05, 0.01, 0.005, 0.001]})

In [111]:
gs.fit(Xtr, ytr)

GridSearchCV(cv=None, error_score='raise',
       estimator=GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features='sqrt', max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'learning_rate': [0.05, 0.01, 0.005, 0.001]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [112]:
ypredgsgbt=gs.predict(Xtest)

In [113]:
precision_recall_fscore_support(ytest, ypredgsgbt)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.        ,  0.7459177 ,  0.68317161]),
 array([ 0.        ,  0.19408566,  0.96416846]),
 array([ 0.        ,  0.30802428,  0.79970436]),
 array([   32,  5884, 10661]))

In [168]:
f1_score(ytest, ypredgsgbt, average='weighted')

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.62363895903984445

In [102]:
clfgbt.fit(Xtr, ytr)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features='sqrt', max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

In [103]:
ypredgbt=clfgbt.predict(Xtest)

In [104]:
precision_recall_fscore_support(ytest, ypredgbt)

(array([ 0.        ,  0.65082202,  0.70336769]),
 array([ 0.        ,  0.30948334,  0.90901416]),
 array([ 0.        ,  0.4194886 ,  0.79307664]),
 array([   32,  5884, 10661]))

In [114]:
##Gradient Boosting Classifer with n=1000
clfgbt1000=GradientBoostingClassifier(n_estimators=1000,max_features="sqrt")

In [115]:
#Tuning the hyper parameters using GridSearchCV
gsgbt1000 =GridSearchCV(clfgbt1000, param_grid={'learning_rate': [0.05, 0.01, 0.005, 0.001]})

In [116]:
gsgbt1000.fit(Xtr, ytr)

GridSearchCV(cv=None, error_score='raise',
       estimator=GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features='sqrt', max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=1000, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'learning_rate': [0.05, 0.01, 0.005, 0.001]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [117]:
ypredgsgbt1000=gsgbt1000.predict(Xtest)

In [118]:
precision_recall_fscore_support(ytest, ypredgsgbt1000)

(array([ 0.5       ,  0.62057143,  0.71449331]),
 array([ 0.03125   ,  0.36913664,  0.87627802]),
 array([ 0.05882353,  0.4629156 ,  0.78715875]),
 array([   32,  5884, 10661]))

In [170]:
f1_score(ytest, ypredgsgbt1000, average='weighted')

0.67066279439507781

In [164]:
cmgsgbt1000=pd.crosstab(ytest, ypredgsgbt1000, rownames=['True'], colnames=['Predicted'], margins= True)

In [165]:
cmgsgbt1000

Predicted     Fatality  Injury  Prop. Damage    All
True                                               
Fatality             1       9            22     32
Injury               1    2172          3711   5884
Prop. Damage         0    1319          9342  10661
All                  2    3500         13075  16577

In [230]:
cv_score(gsgbt1000, Xtest, ytest)

0.69367223589816374

In [119]:
#AdaBoostClassfier with default n=50
from sklearn.ensemble import AdaBoostClassifier

In [121]:
clfada=AdaBoostClassifier()

In [130]:
clfada.fit(Xtr, ytr)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [131]:
ypredclfada=clfada.predict(Xtest)

In [132]:
precision_recall_fscore_support(ytest, ypredclfada)

(array([ 0.18181818,  0.59842001,  0.69840331]),
 array([ 0.0625    ,  0.30897349,  0.8862208 ]),
 array([ 0.09302326,  0.40753194,  0.78118153]),
 array([   32,  5884, 10661]))

In [172]:
f1_score(ytest, ypredclfada, average='weighted')

0.64722633638626215

In [126]:
#AdaBoostingClassifier with n=500
clfada500=AdaBoostClassifier(n_estimators=500)

In [127]:
clfada500.fit(Xtr, ytr)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=500, random_state=None)

In [128]:
ypredada500=clfada500.predict(Xtest)

In [129]:
precision_recall_fscore_support(ytest, ypredada500)

(array([ 0.10810811,  0.5986483 ,  0.71826991]),
 array([ 0.125     ,  0.39140041,  0.85517306]),
 array([ 0.11594203,  0.47333265,  0.78076561]),
 array([   32,  5884, 10661]))

In [171]:
f1_score(ytest, ypredada500, average='weighted')

0.67035902695488647

In [166]:
cmada=pd.crosstab(ytest, ypredada500, rownames=['True'], colnames=['Predicted'], margins= True)

In [167]:
cmada

Predicted     Fatality  Injury  Prop. Damage    All
True                                               
Fatality             4       6            22     32
Injury              27    2303          3554   5884
Prop. Damage         6    1538          9117  10661
All                 37    3847         12693  16577

In [173]:
##Neural Networks
from sklearn.neural_network import MLPClassifier

In [178]:
clfnn = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)

In [179]:
clfnn.fit(Xtr, ytr)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [180]:
yprednn=clfnn.predict(Xtest)

In [181]:
precision_recall_fscore_support(ytest, yprednn)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.        ,  0.61791643,  0.7138271 ]),
 array([ 0.        ,  0.36692726,  0.87599662]),
 array([ 0.        ,  0.46043933,  0.78664084]),
 array([   32,  5884, 10661]))

In [212]:
##NN with hidden layer sizes=20, iterations=1000
clfnn1 = MLPClassifier(solver='adam',hidden_layer_sizes=20,alpha=1e-5, random_state=1, max_iter=1000)

In [213]:
clfnn1.fit(Xtr, ytr)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=20, learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [214]:
yprednn1=clfnn1.predict(Xtest)

In [215]:
precision_recall_fscore_support(ytest, yprednn1)

(array([ 1.        ,  0.57538007,  0.7316723 ]),
 array([ 0.03125   ,  0.46312033,  0.81258794]),
 array([ 0.06060606,  0.51318267,  0.77001022]),
 array([   32,  5884, 10661]))

In [226]:
cmnn= pd.crosstab(ytest, yprednn1, rownames=['True'], colnames=['Predicted'], margins= True)

In [227]:
cmnn

Predicted     Fatality  Injury  Prop. Damage    All
True                                               
Fatality             1      13            18     32
Injury               0    2725          3159   5884
Prop. Damage         0    1998          8663  10661
All                  1    4736         11840  16577

In [229]:
cv_score(clfnn1, Xtest, ytest)

0.67237741231780834

In [186]:
from scipy import stats
from sklearn.grid_search import RandomizedSearchCV

In [203]:
clfnn2 = MLPClassifier(solver='sgd',alpha=1e-5, random_state=1, max_iter=1000)

In [204]:
#Tuning the hyper parameters using Randomized Search CV
rsnn = RandomizedSearchCV(clfnn2, param_distributions={'learning_rate_init': stats.uniform(0.001, 0.05),'hidden_layer_sizes': stats.randint(4, 50)})

In [205]:
rsnn.fit(Xtr, ytr)

RandomizedSearchCV(cv=None, error_score='raise',
          estimator=MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False),
          fit_params={}, iid=True, n_iter=10, n_jobs=1,
          param_distributions={'hidden_layer_sizes': <scipy.stats._distn_infrastructure.rv_frozen object at 0x1f62a7dd8>, 'learning_rate_init': <scipy.stats._distn_infrastructure.rv_frozen object at 0x1f62a7d68>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          scoring=None, verbose=0)

In [206]:
ypredrsnn=rsnn.predict(Xtest)

In [207]:
precision_recall_fscore_support(ytest, ypredrsnn)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.        ,  0.59375723,  0.72779954]),
 array([ 0.        ,  0.4364378 ,  0.83641309]),
 array([ 0.        ,  0.50308551,  0.77833544]),
 array([   32,  5884, 10661]))

In [209]:
f1_score(ytest, ypredrsnn, average='weighted')

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.67913309479985806

In [210]:
rsnn.best_estimator_

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=20, learning_rate='constant',
       learning_rate_init=0.0024320144877978947, max_iter=1000,
       momentum=0.9, nesterovs_momentum=True, power_t=0.5, random_state=1,
       shuffle=True, solver='sgd', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [211]:
rsnn.best_score_

0.6930904118404119

In [216]:
clfnn3 = MLPClassifier(solver='adam',alpha=1e-5, random_state=1, max_iter=1000)

In [219]:
rsnn3 = RandomizedSearchCV(clfnn3, param_distributions={'learning_rate_init': stats.uniform(0.001, 0.05),'hidden_layer_sizes': stats.randint(4, 50)})

In [220]:
rsnn3.fit(Xtr, ytr)

RandomizedSearchCV(cv=None, error_score='raise',
          estimator=MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False),
          fit_params={}, iid=True, n_iter=10, n_jobs=1,
          param_distributions={'hidden_layer_sizes': <scipy.stats._distn_infrastructure.rv_frozen object at 0x1f7570518>, 'learning_rate_init': <scipy.stats._distn_infrastructure.rv_frozen object at 0x1f7556898>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          scoring=None, verbose=0)

In [221]:
ypredrsnn3=rsnn3.predict(Xtest)

In [222]:
precision_recall_fscore_support(ytest, ypredrsnn3)

//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.        ,  0.57363225,  0.73401622]),
 array([ 0.        ,  0.47399728,  0.80658475]),
 array([ 0.        ,  0.51907687,  0.76859135]),
 array([   32,  5884, 10661]))

In [224]:
rsnn3.best_estimator_

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=13, learning_rate='constant',
       learning_rate_init=0.013761681446035557, max_iter=1000,
       momentum=0.9, nesterovs_momentum=True, power_t=0.5, random_state=1,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)